AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  StickerVideoConverter

  Sample SAM Template for StickerVideoConverter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 2048
    Timeout: 60

Resources:
  FfmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg-layer
      Description: FFmpeg binary
      ContentUri: ffmpeg-layer/
      CompatibleRuntimes:
        - python3.12

  StickerVideoConverter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: StickerVideoConverter
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      AutoPublishAlias: dev
      Layers:
        - !Ref FfmpegLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:HeadObject'
              Resource: 'arn:aws:s3:::*'
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 's3:HeadObject'
              Resource: 'arn:aws:s3:::beststickerapp-videoconvertion-out/*'
      Environment:
        Variables:
          OUTPUT_BUCKET_NAME: beststickerapp-videoconvertion-out

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StickerVideoConverterFunction:
    Description: Sticker Video Converter Lambda Function ARN
    Value: !GetAtt StickerVideoConverter.Arn
    Export:
      Name: StickerVideoConverterFunction

  StickerVideoConverterFunctionIamRole:
    Description: IAM Role for Sticker Video Converter Lambda
    Value: !GetAtt StickerVideoConverterRole.Arn
